### ISSUE TITLE
Error timeout

### ISSUE THREAD

**Issue by devnullsp** [zim32/mysql.dart#16]
Using Maridb 10.6.7
Error timeout with simple connect.
![image](https://user-images.githubusercontent.com/8296894/165272325-1af4f43e-8b05-4f13-9ec8-b0769fcc3c4b.png)

**Comment by zim32** [comment]
I will check using mariadb. This db was not tested

**Comment by zim32** [comment]
Can you try creating connection with secure:false as parameter?

**Comment by zim32** [comment]
I can reproduce error. I will check it out

**Comment by zim32** [comment]
Fixed here https://github.com/zim32/mysql.dart/commit/6367ad87e3f3aca5e5c5949d6d73972b41673d53
Release 0.0.15 should work

**Comment by devnullsp** [comment]
hummm i think i doing wrong:
![image](https://user-images.githubusercontent.com/8296894/165361798-a96224af-763a-48b1-8025-5fffb467ebaa.png)

**Comment by zim32** [comment]
Ok I will add logging and then we can continue

**Comment by zim32** [comment]
So I've created separete branch **logging**
Separate branch is needed, because logging adds overhead, and I don't want any overhead in production code.

So you can add dependency as

```
mysql_client:
    git: https://github.com/zim32/mysql.dart.git
    ref: logging
```

And after dart reinstall package, you must see log messages in console.

**Comment by zim32** [comment]
Please send me this messages, so I can figure out what's happening

**Comment by zim32** [comment]
Ah forget. You must enable assertions to see logs.
F.e. use dart **--enable-asserts** ...

**Comment by devnullsp** [comment]
Sorry for delay i confuse with git and i need to search how use

here is your log:

```
PS C:\PRG\DART\mysql_client_prb\bin> dart --enable-asserts run .\mysql_client_prb.dart
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ #0   MySQLConnection.createConnection (package:mysql_client/src/mysql_client/connection.dart:82:12)
│ #1   main (file:///C:/PRG/DART/mysql_client_prb/bin/mysql_client_prb.dart:6:40)
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ 🐛 Establishing socket connection
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ #0   MySQLConnection.createConnection (package:mysql_client/src/mysql_client/connection.dart:84:12)
│ #1   <asynchronous suspension>
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ 🐛 Socket connection established
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ #0   MySQLConnection._processSocketData (package:mysql_client/src/mysql_client/connection.dart:162:12)
│ #1   MySQLConnection.connect.<anonymous closure> (package:mysql_client/src/mysql_client/connection.dart:122:17)
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ 🐛 Processing socket data. Current state is _MySQLConnectionState.waitInitialHandshake
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ #0   MySQLConnection._processInitialHandshake (package:mysql_client/src/mysql_client/connection.dart:278:12)
│ #1   MySQLConnection._processSocketData (package:mysql_client/src/mysql_client/connection.dart:166:13)
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ 🐛 Processing initial handshake
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ #0   MySQLConnection._processInitialHandshake (package:mysql_client/src/mysql_client/connection.dart:287:12)
│ #1   MySQLConnection._processSocketData (package:mysql_client/src/mysql_client/connection.dart:166:13)
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ 🐛 MySQLPacketInitialHandshake:
│ 🐛
│ 🐛 authPluginDataPart1: [126, 84, 102, 37, 34, 120, 89, 55],
│ 🐛 authPluginDataPart2: [67, 46, 89, 89, 48, 38, 106, 101, 62, 69, 126, 110, 0],
│ 🐛 authPluginName: mysql_native_password,
│ 🐛 capabilityFlags: 2181036030,
│ 🐛 charset: 33,
│ 🐛 connectionID: 134,
│ 🐛 protocolVersion: 10,
│ 🐛 serverVersion: 5.5.5-10.6.7-MariaDB,
│ 🐛 statusFlags: [2, 0]
│ 🐛
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ #0   MySQLConnection._processInitialHandshake.initiateSSL (package:mysql_client/src/mysql_client/connection.dart:292:16)
│ #1   MySQLConnection._processInitialHandshake.initiateSSL (package:mysql_client/src/mysql_client/connection.dart:291:31)
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ 🐛 Initiating SSL connection
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
TimeoutException after 0:00:05.000000: Future not completed


```

**Comment by zim32** [comment]
Please, pass secure: false, to createConnection and try again

**Comment by zim32** [comment]
It seems that there is some problem with establishing TLS connection. Maybe firewall is blocking?

**Comment by zim32** [comment]
Hm. I will try to test. Right now you can disable secure connection. I was thinking to make secure false by default, because it gives some network overhead and if connection is inside local network, which is in most cases true, this makes little sense

**Comment by devnullsp** [comment]
ok, and yes usually is local or private network.
its time to start :)
Thanks a lot,

**Comment by bsutton** [comment]
Just want to add to this that I'm having the same problems.

We are running maria db 10 within a docker container.

If I add the secure: false option then I can connect successfully.

Here is the docker-compose we are working with:
```yaml
version: '3.3'

volumes:
  mysql:

services:
  mysql:
    container_name: mysql
    image: mariadb:latest
    restart: on-failure
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ADMIN_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_SCHEMA}
      TZ: ${TIME_ZONE-Australia/Melbourne}
    command: >
                 --lower-case-table-names=1
                 --bind-address=127.0.0.1
                 --default-authentication-plugin=mysql_native_password
                 --max-allowed-packet=512M
                 --innodb_buffer_pool_instances=${MYSQL_INNODB_BUFFER_POOL_INSTANCES-32}
                 --innodb_buffer_pool_chunk_size=${MYSQL_INNODB_BUFFER_POOL_CHUNK_SIZE-8M}
                 --innodb_buffer_pool_size=${MYSQL_INNODB_BUFFER_POOL_SIZE-512M}
                 --table_open_cache=${MYSQL_TABLE_OPEN_CACHE-512}
                 --max_connections=${MYSQL_MAX_CONNECTIONS-98}
                 --innodb_flush_neighbors=0
                 --innodb_fast_shutdown=2
                 --innodb_flush_log_at_trx_commit=1
                 --innodb_flush_method=fsync
                 --innodb_doublewrite=0 
                 --innodb_use_native_aio=0
                 --innodb_read_io_threads=10
                 --innodb_write_io_threads=10
                 --slow_query_log_file=/tmp/mysql-slow.log --long-query-time=1
                 --slow_query_log

    volumes:
      - mysql:/var/lib/mysql
    network_mode: "host"
    logging:
      driver: "journals"

```

**Comment by bsutton** [comment]
I'm just concerned that you have marked this as a workaround based on turning off the secure option. To be clear, I wouldn't view this as a workaround but a serious security hole.

**Comment by zim32** [comment]
It just means that issue can be temporary fixed f.e. when developing in dev environment or when mysql server and application is inside trusted network. 

I will fix this

**Comment by zim32** [comment]
Good day. Can you try latest release? Maybe it will fix this issue.
